using BantuBantu.Domain;
namespace BantuBantu.Application;

public class OrderService(IMarketplaceRepository repo, ICurrentActor current, IWilayahRepository wilayah) : ApplicationService(current)
{
    private static OrderDto OrderMap(Order o) => new(o.Id, o.ProviderId, o.Provider.FullName, o.Status, o.ScheduledDate, o.Price, o.PricingType, o.AddressDetail, o.VillageId, o.Review is not null);
    public async Task<OrderDto[]> Orders(CancellationToken ct) => (await repo.OrdersAsync(Caller(), ct)).Select(OrderMap).ToArray();
    public async Task<OrderDto> Book(BookingRequest r, CancellationToken ct) { var actor = Customer(); var p = await repo.PublicProviderAsync(r.ProviderId, ct) ?? throw new ProfileException("Penyedia belum tersedia.", 404); var today = DateOnly.FromDateTime(DateTime.UtcNow); if (r.ScheduledDate <= today || r.ScheduledDate > today.AddYears(1) || !p.Availability.Any(a => a.DayOfWeek == r.ScheduledDate.DayOfWeek && a.IsAvailable)) throw new ProfileException("Pilih tanggal mulai besok sesuai ketersediaan penyedia."); if (await wilayah.FindAsync(r.VillageId, ct) is null || r.AddressDetail.Trim().Length < 10) throw new ProfileException("Alamat layanan tidak valid."); var o = new Order { CustomerId = actor.Id, ProviderId = p.Id, Provider = p, ScheduledDate = r.ScheduledDate, Price = p.Price, PricingType = p.PricingType, VillageId = r.VillageId, AddressDetail = r.AddressDetail.Trim() }; repo.AddOrder(o); await repo.SaveAsync(ct); return OrderMap(o); }
    public async Task<OrderDto> ChangeOrder(Guid id, OrderStatusRequest r, CancellationToken ct) { var actor = Admin(); var o = await repo.OrderAsync(actor, id, ct) ?? throw new ProfileException("Pesanan tidak ditemukan.", 404); if (!((o.Status == OrderStatus.Pending && r.Status is OrderStatus.Confirmed or OrderStatus.Cancelled) || (o.Status == OrderStatus.Confirmed && r.Status is OrderStatus.Completed or OrderStatus.Cancelled))) throw new ProfileException("Perubahan status tidak diizinkan.", 409); o.Status = r.Status; if (r.Status == OrderStatus.Completed) o.Provider.JobsCompletedCount++; repo.Audit(actor, o.ProviderId, "order.status", $"{id}: {r.Status}"); await repo.SaveAsync(ct); return OrderMap(o); }
    public async Task<ReviewDto> Review(Guid id, ReviewRequest r, CancellationToken ct) { var actor = Customer(); var o = await repo.OrderAsync(actor, id, ct) ?? throw new ProfileException("Pesanan tidak ditemukan.", 404); if (o.Status != OrderStatus.Completed || o.Review is not null) throw new ProfileException("Ulasan hanya sekali untuk pesanan selesai.", 409); if (r.Comment.Trim().Length < 3) throw new ProfileException("Ulasan minimal 3 karakter."); var review = new Review { OrderId = o.Id, ProviderId = o.ProviderId, CustomerId = actor.Id, Rating = r.Rating, Comment = r.Comment.Trim() }; repo.AddReview(review); await repo.SaveAsync(ct); return new(review.Rating, review.Comment, review.CreatedAt); }
}
